// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250407223705_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("Domain.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Channels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7eb8cb57-fac4-4e70-a685-5be6ac749540"),
                            Description = "Canal dedicado a dotnet core",
                            Name = "DotnetCore"
                        },
                        new
                        {
                            Id = new Guid("6455d5e4-0db3-48aa-a893-266ee48a52fa"),
                            Description = "Canal dedicado a Angular",
                            Name = "Angular"
                        },
                        new
                        {
                            Id = new Guid("bc42c9b2-6ce0-4400-bbf7-3c3f9356e56d"),
                            Description = "Canal dedicado a Reactjs",
                            Name = "Reactjs"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
